name: Run Python Script Daily

on:
  schedule:
    # Run at 8:30 a.m. UTC every day
    - cron: '30 8 * * *'
permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
      APP_KEY: ${{ secrets.APP_KEY }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      OAUTH2_REFRESH_TOKEN: ${{ secrets.OAUTH2_REFRESH_TOKEN }}   

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.12'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install pip==23.2.1
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

    - name: Run Python script
      run: python smos-numeric.py
